In [10]:
#For singel line comment we use "#"
'''
For multiple line commentation 
we have to use 
3 single quation
upside and the downside of the lines.
'''
print('jenny')
print("01682013034")
print("jenny \n jakia \t sultana") #backslash character or escape sequence

jenny
01682013034
jenny 
 jakia 	 sultana


In [15]:
#variables
name = "jenny" # character varible is used with + sign means concatination
age = 25
print("Our new student name is " +name)
print(name + " lives in Dhaka.")
print("She is currenty", age, "years old.") # int or flot is used with comma


Our new student name is jenny
jenny lives in Dhaka.
She is currenty 25 years old.


In [25]:
#Basic numerical operator +, -, *, /, %, //(Floor), **(Exponentiation)
a = 19
b = 4
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b) 

print(a//b) #used for floor
print(a**b) # used for exponentiation[a to the power of b]

23
15
76
4.75
3
4
130321


In [29]:
#Getting user input

# This is manual process
name = "jenny"
age = "26"
GPA = "3.65"
print("Student Information")
print(".................")
print("Name : "+name)
print("Age : "+age)
print("CGPA :"+ GPA)

#from user taking the value with imput() function
name = input("Enter your name: ")
age = input("Enter your age: ")
GPA = input("Enter you CGPA: ")

print("Student Information")
print(".................")
print("Name : "+name)
print("Age : "+age)
print("CGPA : "+ GPA)



Student Information
.................
Name : jenny
Age : 26
CGPA :3.65
Enter your name: k
Enter your age: 5
Enter you CGPA: 3
Student Information
.................
Name : k
Age : 5
CGPA : 3


In [41]:
#Type casting
#user input always string e hoy
num1 = input("Enter first number: ")
num2 = input("Enter second number: ")
sum = int(num1) + int(num2) #conveting string to int
print("The sum is" , sum)

sub = int(num1) - int(num2) #conveting string to int
print("The substraction is" , sub)

# this process requires so much type casting rater we can change the type while tking inputs

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
print( num1+num2)
print( num1 -num2)


Enter first number: 3
Enter second number: 4
The sum is 7
The substraction is -1
Enter first number: 10
Enter second number: 9
19
1


In [43]:
#Area of a shape
#triangle
b = float(input("Enter the base of  triangle:"))
h = float(input("Enter height"))
Area = 0.5*b*h
print("Area of a trinage", Area)

Enter the base of  triangle:4
Enter height3
Area of a trinage 6.0


In [50]:
#Math realted library Function
from math import *
print(max(20,30)) #max(a,b) will find the max
print(min(20,30))
print(abs(-4))
print(sqrt(5))
print(pow(20,3))
print(round(2.6))
print(floor(3.7))
print(ceil(2.9))


30
20
4
2.23606797749979
8000.0
3
3
3


In [65]:
#Formatting string | Type Function
num = "20.5"
print(type(num)) # type() will return the type of value

print(type(False))

#string formatting 20 + 30 =50
num1 = 20
num2 = 30
print(f"{num1} + {num2} = {num1+num2} ")

#print in single line with two print()
print("Jakia Sultana", end = " ") #by default print() endup with newline but here we put space after the line
print("ID: 11508023")
 

<class 'str'>
<class 'bool'>
20 + 30 = 50 
Jakia Sultana ID: 11508023


In [69]:
#Relational Operators and Boolean Data types
# < > <= >= == != # result will be in boolean
print(2>3)
print(3<=5)
print("Jenny"=="jenny")
print(3.14 != 3.114)

False
True
False
True


In [78]:
#Control Statement 
#conditional control statement(if, else, elif)
#loop control statement(for, while)
marks = int(input("Enter your marks: "))
if(marks >= 33):
    print("Passed")
    print("Congrats!")
if(marks<33): 
    print("Failed")  
    print("Better next time")
    


Enter your marks: 22
Failed
Better next time


In [80]:
#else if = elif
'''statement1 = if statement
statement 2 = if, else statement
statement 3 or more = if, elif....else statement '''
#Grading sytem 
marks = int(input("Enter your marks : "))
if(marks >= 80):
    print("A+")
elif(marks >= 70):
    print("A")
elif(marks >= 60):
    print("A-")
elif(marks >= 50):
    print("B")
elif(marks >= 40):
    print("C")
else:
    print("F")


Enter your marks : 11
F


In [82]:
#Inner if statement or nested if
#code to find largest among three
num1  = int(input("Enter num1 :"))
num2 = int(input("Enter num2:"))
num3 = int(input("Enter num3:"))

if num1 > num2 :
    if num1> num3:
        print("largest number is: ", num1)
    else:
        print("largest number is: ", num3)
if(num2 > num1):
    if(num2 > num3):
        print("largest number is: ", num2)
    else:
        print("largest number is: ", num3)



Enter num1 :20
Enter num2:35
Enter num3:17
largest number is:  35


In [83]:
#Ternary operator
# largest among 2
num1= 10
num2= 20
print(num1 if num1> num2 else num2) # 3 operation in one line


20


In [89]:
#logical oeprator and or not
#largest among 3
"""
num1  = int(input("Enter num1 :"))
num2 = int(input("Enter num2:"))
num3 = int(input("Enter num3:"))

if num1>num2 and num1>num3:
    print("Largest Number is: ", num1)
elif num2>num1 and num2> num3:
    print("Largest Number is: ", num2)
else:
    print("Largest Number is: ", num3)
"""
    
#vowel and consonet ditection
ch = input("Enter a character  : ")

if ch=='a' or ch == 'e' or ch =='i' or ch== 'o' or ch=='u':
    print("Vowel")
else:
    print("consonent")


Enter a character  : q
consonent


In [92]:
#Code of letter grade using logical operator
marks = int(input("Enter your marks: "))
if marks>=80 and marks<100:
    print("A+")
elif marks>=70 and marks<80:
    print("A")
elif marks>=60 and marks<70:
    print("B")
elif marks>=50 and marks<60:
    print("C")
else:
    print("F")

Enter your marks: 56
C


In [95]:
#while Loop
#print 1 to 100
i = 1
while (i<=100):
    print(i)
    i = i+1
print("End")

#even numbers
i = 2
while (i<=100):
    print(i)
    i = i+2
print("End")

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
End
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100
End


In [101]:
#sum of n numers
n = int(input()) 
i =1
sum = 0
while(i<=n):
    sum = sum+i
    i = i+1
    
print("Total sum : ", sum)
    


100
Total sum :  5050


In [105]:
#break and contiue only use in if condition
i = 1
while (i<=100):
    if i == 20:
        continue # contiue er niche kno kaj korbe na abr loop e fire jabe
        #break # loop theke ber hote break use kori
    print(i)
    i = i+1
print("End")

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


KeyboardInterrupt: 

In [113]:
#List is a python's object where we can store multiple items
subjects = ["C","C++","Java","Python"] 
print(subjects)
#list er item index 0 theke suru hoy
print(subjects[1:])
print(subjects[-1]) #last the print korate caile

print("Javascript" in subjects) # in and not in can be used in list

print(subjects + ["Javascript", 101]) # adding items in list



['C', 'C++', 'Java', 'Python']
['C++', 'Java', 'Python']
Python
False
['C', 'C++', 'Java', 'Python', 'Javascript', 101]


In [136]:
#List 
subjects = ["C","C++","Java","Python","R","Ruby"]
print(len(subjects)) #lenght of list start from 1
subjects.append("basic") # add element at the last

subjects.insert(2,"Android") #index 2 te insert korlm
subjects.remove("C++") # removing particular items
#subjects.sort() #sorting alphabetically
subjects.reverse() #last to first item showing
#subjects.pop() # remove the last item
#subjects.clear() #clearing all items

subjects2 = subjects.copy()
print(subjects)
print(subjects2)

position = subjects.index("Java") #return position of particular item
print(position)
count = subjects.count("Java") # count the items if it is more than one in list
print(count)




6
['basic', 'Ruby', 'R', 'Python', 'Java', 'Android', 'C']
['basic', 'Ruby', 'R', 'Python', 'Java', 'Android', 'C']
4
0


In [5]:
#range - ekta range e value generate kora ..0 theke start kore
num = list(range(10)) # 0 theke 9 print korbe
print(num)
print(num[3])

num = list(range(5,11)) # 5 theke 10porjnto print korbe
print(num)

num = list(range(5,100,2)) # 5 theke 100 porjnto print korbe and interval 2
print(num)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
3
[5, 6, 7, 8, 9, 10]
[5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]


In [2]:
#for loop

num = [10, 20, 30, 40, 50, 60]
print(num)

#using while loop print each value of list
index =0
n = len(num)
while(index < n):
    print(num[index])
    index = index+1
    
    
#using for loop print each value of list
for x in num:
    print(x)



[10, 20, 30, 40, 50, 60]
10
20
30
40
50
60
10
20
30
40
50
60


In [7]:
#Series program
'''
#1+2+3....+n

n = int(input("Enter the last num: "))
num = (range(n)
sum = 0
for x in num:
    sum = sum + x
print(sum)

'''
n = int(input("Enter the last num: "))
sum = 0
for x in range(1, n+1, 1):
    sum = sum + x
print(sum)




Enter the last num: 10
55


In [15]:
'''
# 2+4+6+.....+n (sum of even numbers from 1 to n)
n = int(input("Enter the last number: "))
sum = 0
for x in range(2, n+1, 2): 
    sum = sum + x
    print(x)
print(sum)

# 1+3+5+7+.....+n (sum of odd numbers from 1 to n)
n = int(input("Enter the last number: "))
sum = 0
for x in range(1, n+1, 2): 
    sum = sum + x
    print(x)
print(sum)

#4+8+12+...+n
n = int(input("Enter the last num of series: " ))
sum = 0
for x in range(4, n+1, 4):
    sum = sum + x
    print(x)
print(sum)
'''

#1^2 + 2^2 +3^2+....+n^2
n = int(input("Enter the last num of series: " ))
sum = 0
for x in range(1,n+1, 1):
    sum = sum + (x*x)
print(sum)
    



Enter the last num of series: 3
14


In [16]:
# 1 + 1/2 +1/3+ ...+ 1/n
n = int(input("Enter the last num of series: " ))
sum = 0
for x in range(1,n+1, 1):
    sum = sum + (1/x)
print(sum)

Enter the last num of series: 2
1.5


In [8]:
# find a prime number
from math import *
num = int(input("Enter a number to check prime number: "))
Flag = False
for x in range (2, ceil(num/2)):
    if(num%x == 0):
        Flag = True
    break
if Flag== True:
    print("Not a prime number")
else:
    print("Prime number")
    


Enter a number to check prime number: 2
Prime number


In [15]:
#pattern
"""
*
**
***
****
"""
x = int(input("Enter the number: "))
for i in range(1,x+1):
    print(i*"*")

Enter the number: 5
*
**
***
****
*****


In [13]:
"""
*   2*I -1
***
*****
*******
"""
x = int(input("Enter the number: "))
for i in range(1,x+1):
    print(((2*i)-1)*"*")

Enter the number: 5
*
***
*****
*******
*********


In [1]:
#guessing number by generating random values
import random
"""
guessNum = int(input("Enter your guess num between 1 to 5 :"))
randomNumber = random.randint(1,5) # small range er random value generate korle evabe range deya valo
#randomNumber = random.random()*100 # large range e random num geneate korte caile
if guessNum == randomNumber:
    print("Won")
else:
        print("lost")
        print("random number waS: ", randomNumber)
 """       
for x in range(1,6):
    guessNum = int(input("Enter your guess num between 1 to 5 :"))
    randomNumber = random.randint(1,5)
    
    if guessNum == randomNumber:
        print("Won")
    else:
        print("lost")
        print("random number waS: ", randomNumber)
    

Enter your guess num between 1 to 5 :4
Won
Enter your guess num between 1 to 5 :1
lost
random number waS:  3
Enter your guess num between 1 to 5 :4
Won
Enter your guess num between 1 to 5 :5
lost
random number waS:  2
Enter your guess num between 1 to 5 :6
lost
random number waS:  2


In [4]:
#list as input from user
"""
input = 10 20 30 40 set of number string
out= summation of numbers
"""
n = input("Enter a text of numbers: ")
list= n.split() # 10, 20, 30 mane sob string gulo alada
sum = 0

for num in list:
    sum = sum + int(num)
print(sum)



Enter a text of numbers: 12 1 2 6
21


In [8]:
#finding the number of word, digits and letter from a list input
numOfWords = 0
numofLetters = 0
numOfDigits = 0
text = input("Enter a text of numbers : ") #My name is 123

for x in text:
    x = x.lower()
    if x >= 'a' and x <= 'z':
        numofLetters = numofLetters + 1
    elif x >= '0' and x <= '9':
        numOfDigits = numOfDigits + 1
    elif x == ' ':
        numOfWords = numOfWords + 1
    
print(numofLetters)
print(numOfDigits)
print(numOfWords+1)
        
         
    

Enter a text of numbers : bangla desh 1149 qw
12
4
4


In [3]:
#matrix is 2D list or array
matrix = [
    [1,2,3],
    [4,5,6]   
]
matrix[0][2]= 10 # to change the value of matrix
print(matrix[0][2])

# to print the value of matrix using loop
for row in matrix:
    for col in row:
        print(col)
        


10
1
2
10
4
5
6


In [9]:
#Dictionary
'''
Kye -> value pair

Name -> Jakia Sultana 
Email -> jenny15cu@gamil.com
Age -> 25

'''
studentId = {
    "101": "Jakia Sultana",
    "102": "Fariha Sultana",
    "103": "Marjana Akhter",
    
    
}
print(studentId["101"]) # to print particular key or,
print(studentId.get("102")) #using get function we can print

print(studentId.get("105")) # it will give "none"as output
print(studentId.get("105", "Not a valid key")) # if the key is not present then it will print this msg

print(studentId.get("103", "Not a valid key")) # if the key is present then it will print that keys value




Jakia Sultana
Fariha Sultana
None
Not a valid key
Marjana Akhter


In [15]:
#tuples are used to store multiple items in a single variable
#a tuple is a collection which is ordered and unchangeable


students = (("Jakia", 25, "From Comilla")# tuple can store tuple
            ,"sultana","jenny","toma")
print(students[0])
#tuple slicing
print(students[1:])

('Jakia', 25, 'From Comilla')
('sultana', 'jenny', 'toma')


In [23]:
#set are used to store multiple items in a single variable which are unordered and unindexed
# no duplicate values
#no index access
num1 = {1,2,3,4,5,5,5} # though 5 3bar ache but print hbe 1bar
num2 = set([3,4,7,8,9]) #another way to create set with set func
num2.add(19)
num1.remove(4)
print(num1)
print(num2)

#real use of set
print(num1 | num2)
print(num1 & num2)
print(num1 - num2)


{1, 2, 3, 5}
{3, 4, 7, 8, 9, 19}
{1, 2, 3, 4, 5, 7, 8, 9, 19}
{3}
{1, 2, 5}


In [29]:
#stack LIFO
books = [] #empty list
books.append("Learn C")
books.append("Learn C++")
books.append("Learn Python")
books.append("Learn Java")
print(books)

books.pop()
print("Now the top book is: ",books[-1])

books.pop()
print("Now the top book is: ",books[-1])

books.pop()
print("Now the top book is: ",books[-1])

books.pop()
if not books:
    print("No book left")



['Learn C', 'Learn C++', 'Learn Python', 'Learn Java']
Now the top book is:  Learn Python
Now the top book is:  Learn C++
Now the top book is:  Learn C
No book left


In [32]:
#Queue FIFO
#Queue doesn't work as stack as after popoing every item change its position
from collections import deque

bank = deque(["anis","jenny","jisan"])
bank.popleft()
print(bank)

bank.popleft()
print(bank)

bank.popleft()
print(bank)

if not bank:
    print("No one left")

deque(['jenny', 'jisan'])
deque(['jisan'])
deque([])
No one left


In [35]:
#Function [User defined function]
def add(a,b):
    sum = a+b
    print(sum)
    
add(10,20)
message()

#parameter less function
def message():
    print("No Parameter")


30
No Parameter


In [36]:
#returning value from function
def add(a,b):
    sum = a+b
    return sum
result = add(20,30)
print("Result = ", result)

# find largest among two
def large(a,b):
    if a>b:
        return a
    else:
        return b

print(large(10,30))

Result =  50
30


In [51]:
# xarg and xxarg
"""
def student(id, name):
    print(id, name)
    
student(11508023, "jenny")
# jodi beshi data dekhate chai tahole function er parameter o beshi dite hbe
# but xarg use korle parameter change na korei beshi agument pass kor ajabe
"""
def student(*details):
    print(details)

student("jakia Sultana", 11508023, "jenny15cu@gmail.com")#return value as tuple

#using xarg we calculate summation

def add(*numbers): # *numbers means xargs
    sum = 0
    for num in numbers:
        sum = sum + num
    print(sum)
    
add(10,15)
add(22,23,56)
add(12,54,78,98)

#xxargs [key value pair or dictionaryr mto kaj kore]
# arbitrary keyword argument
def students(**detail):
    print(detail['id'])
    
students(id= 11508023, name= " Jakia Sultana", cgpa = 3.5)


('jakia Sultana', 11508023, 'jenny15cu@gmail.com')
25
101
242
11508023


In [53]:
#Lamda Function
# A function without name(annonymous function)
# Not powerful as Named function
# It can work with single expression/ single line of code

def calculation(a,b):  #named function
    return a*a + 2*a*b +b*b

a = (lambda a,b: a*a + 2*a*b +b*b) (2,3) #annonymous func

print(calculation(10,20))
print(a)


900
25


In [2]:
#Map and Filter function
# work with list
#map has 2 parameter. function and llist


def square(a):
    return a*a
num = [1,2,3,4,5]
result= list(map(square, num))
print(result)

#filter function
#it will remove the items from list which is not matched in the funcc=tion
number = [10,21,34,41,53]
result2 = list(filter(lambda x : x%2 ==0, number))
print(result2)


[1, 4, 9, 16, 25]
[10, 34]


In [11]:
#List comprehension
number2 = [10,21,34,41,53]
result2 = list(filter(lambda x : x%2==0, number2))
print(result2)

#his work can be done more easily with list comprehension
#syntax = [expression for item in list]
# expression = x*x, item = x, list = number


number = [1,2,3,4,5]
#result= [x*x for x in number]
result= [x for x in number if x%2==0]
print(result)


[10, 34]
[2, 4]


In [14]:
#zip function
roll = [1,2,3,4,5,6,7]
name = ["mosiur", "abu bakar","sabbir","tanim","shipra","dipto","sathi"]
section = "ABABAB"
print(list(zip(roll, name, section))) #generate tuples


[(1, 'mosiur', 'j'), (2, 'abu bakar', 'e'), (3, 'sabbir', 'n'), (4, 'tanim', 'n'), (5, 'shipra', 'y'), (6, 'dipto', 'q')]


In [16]:
#recursion
#factorial problem

def factorial(n):
    if n==1:
        return 1
    else:
        return n * factorial(n-1)
    
result= factorial(5)
print(result)

120


In [34]:
#Reading a file
file = open("Anisul.txt", "r+") # r+ means read and write
print(file.readable()) #check the file readable or not
"""
text = file.read() # to read the file
print(text)
size = len(text) # total lenght of character in this file
print(size)

textline = file.readlines()[0] # read the lines in this textfile
print(textline)
"""
for line in file:
    print(line)
file.close()

True
Jakia from dept of cse

kaniz from math

shanta from ict

jalal from eng


In [36]:
#writing in a file
# only "w" dile new text previous text k overwrite korbe
file= open("Anisul.txt","a") # a means append ager ja ache tar sathe new add
file.write("\n Sumi from Bangla")

file.close()

 # Python Libraries
 

#                    Numpy
NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is used for linear algebra, fourier transform, and matrics.


In [37]:
#create a numpy array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr)) # array object in Numpy is ndarray

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [39]:
# to ckeck numpy version
import numpy as np
print(np.__version__)

1.16.2


### ndim attribute returns dimensions
### ndmin used to set the dimension 

In [44]:
#Dimensions in array
import numpy as np

a = np.array(10) #0D array - single element
b = np.array([1,2,3,4,5]) #1D array - 0D arrays
c = np.array([[1,2,3,4],[5,6,7,8]]) #2D array/matrix - 1D arrays
d = np.array([[[1,2,3,4],[5,6,7,8]],[[10,21,32,43],[53,64,76,86]]]) #3D array - 2D arrays

print(a.ndim)# ndim attribute returns an int to tell how many dimensions that array have
print(b.ndim)
print(c.ndim)
print(d.ndim)

#Higher Dimensional Arrays

arr = np.array([1,2,3,4], ndmin = 5) # ndmin means num of dimension
print(arr)
print('number of dimensions: ', arr.ndim)

0
1
2
3
[[[[[1 2 3 4]]]]]
number of dimensions:  5


In [1]:
#Numpy Array Indexing

#access Array elements
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[3]+arr[4])#access 4th n 5th element and add them

#access 2D array
arr2 = np.array([[3,5,7],[8,9,3]])
print(arr2[1,0])#1st element of 2nd dimesion

#access 3D array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr3[0, 1, 2])

"""
arr3[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6
""" 
#nregative indexing
arr4 = np.array([1,2,3,4,5,6])
print(arr4[-2])

1
9
8
6
5


In [7]:
#Numpy Array slicing
"""
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

"""

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:5]) #start index 1 to index 4.. 5 dile 4 porjnto print hbe
print(arr[1:4:2]) #last one step mane koto ghor por por print hbe
print(arr[:7]) #0 theke 6th index porjnto value print
print(arr[4:]) #slice element from index 4 to end
print(arr[:4]) 
print(arr[-3: -1])

print(arr[::2]) # stat from 0 index to end and step is 2
#slicing 2D array
arr2 =np.array([[1,2,3,4],[5,6,7,8]])
print(arr2[0, 1:3]) # from 1st row print index 1 to 3



[2 3 4 5]
[2 4]
[1 2 3 4 5 6 7]
[5 6 7 8]
[1 2 3 4]
[6 7]
[1 3 5 7]
[2 3]


In [9]:
#from both element return index 2
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 2])

#from both element, slice 1 to index 4
print(arr[0:2, 1:4])

[3 8]
[[2 3 4]
 [7 8 9]]


In [16]:
#NumPy Data type
"""
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
"""
arr = np.array(['08-05-21'])
print(arr.dtype) #dtype to know the datatype
#creating array with defined datatype

arr2 = np.array([1,2,3,4], dtype = 'S')
print(arr2)
print(arr2.dtype)

<U8
[b'1' b'2' b'3' b'4']
|S1


#### Converting Datatype with astype() function

In [17]:
#converitng datatype on existing array
#using astype() function
arr = np.array([1.3,3.1,3.7,4.2])
#copying this array to new variable
newarr = arr.astype(int)
print(newarr,arr)

[1 3 3 4] [1.3 3.1 3.7 4.2]


In [18]:
#NumPy array Copy vs View
#copy() is a new array and own the data, any changes here doesnt affect the original array
#view() is just a view of original data, any change can affect the original array

import numpy as np
arr = np.array([10,12,34])
x = arr.copy()
arr[0] = 32
print(arr)
print(x)


[32 12 34]
[10 12 34]


In [19]:
arr = np.array([10,12,34])
x = arr.view()
x[2] = 11
print(arr)
print(x)
#changes in view array can affect original one

[10 12 11]
[10 12 11]


In [20]:
#to check whether copy and view array has any value
#using base attribute
#if there is value it will return none
#if doesn't have value it will return original array
arr = np.array([10,12,34])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[10 12 34]


In [24]:
#Shape of an array
arr = np.array([[1,2,3,4],[6,7,8,9]])
print(arr.shape)
#shape attribute will return the dimension ansd number of element in each dimension

arr2 = np.array([1,2,3,4], ndmin = 5) #creating 5D array
print(arr2)

(2, 4)
[[[[[1 2 3 4]]]]]


In [1]:
#Reshapping Array  
#by reshaping we can change the dimension
#reshape 1D to 2D
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3) # 4arrays each with 3 elements
print(newarr)
#Reshape from 1D to 3D
newarr2 = arr.reshape(2,3,2)# 2 arrays that contains 3 array and each contains 2 element
print(newarr2)
print(arr.reshape(2,6).base)#check copy or view

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [2]:
#unknown dimension
#pass -1 as value and numpy will calculate this number
import numpy as np
arr = np.array([11,12,13,14,15,16,17,18])
newarr = arr.reshape(2,2,-1) #2main arrays with 2 arrays and num of element unknown that's why -1
print(newarr)

[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]


In [3]:
#Flattening the arrays
#Flattning means converting a multidimensional array to 1D
#we use reshape(-1) for it
arr = np.array([[1,2,3,4],[5,6,7,8]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6 7 8]


In [1]:
#Numpy Array Iteration
#iterating 1D array 
import numpy as np
arr = np.array([1,2,3,4,5])
for x in arr:
    print(x)
print("Iteration End of 1D array\n")

#Iterating 2D array
arr2 = np.array([[1,2,3],[4,5,6]]) 
for x in arr2:
    print(x)
print("Iteration End of 2D array with dimension\n")    

#iterate on each scalar element means ek line ei sob element dekhabe dimension wise na
#using nditer()
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
for x in np.nditer(arr3):
    print(x)
print("Iteration End of 2D array in one line using nditer() function\n") 

#Iterating array with different data types
#op_dtypes argument used to change the datatype of array
#numpy doesn't allow to change its datatype in place thats why we need another place called buffer
#we pass flags=['buffered']

arr4 = np.array([1,2,3,4,5])
for x in np.nditer(arr4, flags = ['buffered'], op_dtypes = 'S'):
    print(x)
print("Coverted the Datatype of array using op_dtypes and buffer arguments\n") 


#iterate through every scalar element of the 2D array skipping 1 element

arr5 = np.array([['a','b','c','d'],['e','f','g','h']])
for x in np.nditer(arr5[0:2, ::2]):
    print(x)
print("using 2D array slicing we printed element with step 2\n")


#enumerated Iteration using ndenumerate() in 1D array
arr6 = np.array([1,2,3])
for indx, x in np.ndenumerate(arr6):
      print(indx, x)
print("Enumeration used to count the index of 1D with value\n")

#enumerated Iteration using ndenumerate() in 2 array
arr7= np.array([[1,2,3],[4,5,6]])
for indx, x in np.ndenumerate(arr7):
      print(indx, x)
print("Enumeration used to count the index of 2D with value\n")   

1
2
3
4
5
Iteration End of 1D array

[1 2 3]
[4 5 6]
Iteration End of 2D array with dimension

1
2
3
4
5
6
7
8
9
Iteration End of 2D array in one line using nditer() function

b'1'
b'2'
b'3'
b'4'
b'5'
Coverted the Datatype of array using op_dtypes and buffer arguments

a
c
e
g
using 2D array slicing we printed element with step 2

(0,) 1
(1,) 2
(2,) 3
Enumeration used to count the index of 1D with value

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
Enumeration used to count the index of 2D with value



In [22]:
#Numpy Joining Array
#joining two or more array in a single array by axes
#usin comcatenate() function aomg with axis
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr = np.concatenate((arr1,arr2)) #axis = 0 by default
print("\nJoin of two 1D array",arr)
print("\n")

#joing 2D array along rows axis = 1

arr3 =np.array([[1,2],[3,4]])
arr4 = np.array([[5,6],[7,8]])

arrr = np.concatenate((arr3,arr4),axis =1) #axis=0 means horizontally(x axis) and axis=1 means goes vertically(y axis)
print("Join of 2D array horizontally\n",arrr)
print("\n")

#joing array with stack function
#stacking is done along a new axis

arr5 = np.array([1,2,3,4])
arr6 = np.array([5,6,7,8])

arr_stack = np.stack((arr5,arr6),axis=1)
print("Using stack 1D arrays are joined together",arr_stack) #using a diff axis 
print("\n")

#to stack along rows
arr_stack_rows = np.hstack((arr5,arr6))
print("To stack along rows", arr_stack_rows)
print("\n")

#to stack along columns
arr_stack_columns = np.vstack((arr5,arr6))
print("To stack along columns", arr_stack_columns)
print("\n")

#to stack along height or depth
arr_stack_depth = np.dstack((arr5,arr6))
print("To join along depth\n",arr_stack_depth)


Join of two 1D array [1 2 3 4 5 6 7 8]


Join of 2D array horizontally
 [[1 2 5 6]
 [3 4 7 8]]


Using stack 1D arrays are joined together [[1 5]
 [2 6]
 [3 7]
 [4 8]]


To stack along rows [1 2 3 4 5 6 7 8]


To stack along columns [[1 2 3 4]
 [5 6 7 8]]


To join along depth
 [[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [34]:
#Numpy splitting Array
#splitting is reverse operation of joining
#using array_split() function we will split it
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
newarr = np.array_split(arr,3)#3 mean 3 part e split
print("Splitting an array into. 3 parts\n",newarr)
print("\n")

'''
If the array has less elements than required, 
it will adjust from the end accordingly.

'''
#Access the splitted array
print(newarr[0])
print(newarr[1])
print(newarr[2]) #splitted array can be accessed from result
print("\n")

#splitting 2D array to 3 2D arrays
arr2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr2 = np.array_split(arr2,3)
print(newarr2)
print("\n")


#we can also define the axis
newarr3 = np.array_split(arr2,3,axis=1)#split along y axis from each array
print(newarr3)
print("\n")

#split horizontally
newarr4 = np.hsplit(arr2,2)#split horizontally
print(newarr4)
print("\n")
newarr5 = np.vsplit(arr2,2)#split vertically
print(newarr5)
print("\n")

Splitting an array into. 3 parts
 [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


[1 2 3]
[4 5 6]
[7 8 9]


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32)]


[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])]


[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[ 7,  8],
       [ 9, 10],
       [11, 12]])]




In [38]:
#Numpy searchimg Arrays
#using where() method
arr = np.array([1,2,3,4,3,6,3,9])
x = np.where(arr == 3)
print(x)

#Searchsorted() performs a binary search where we wn inset the search value
#this searchcorted() used on sorted array
arr1 = np.array([5,6,7,7,8])
x1 = np.searchsorted(arr1, 7)#will find the location of 7
print(x1) #return the index 
#By default the search is from lest side but we can start it from right aso
x2 = np.searchsorted(arr1,7, side ='right')
print(x2)

x3 = np.searchsorted(arr1, [2,4,8])
print(x3) #return the index where we can add this numbers


(array([2, 4, 6], dtype=int64),)
2
4
[0 0 4]


In [41]:
#Sorting Array
#using sort() method we do sorting
#it returns a copy of the array
arr1 = np.array([3,0,6,2,8,1])
print("sorting numbers",np.sort(arr1))
print("\n")

arr2 = np.array(["banana","orange","apple","cherry"])
print("sorting string alphabetically", np.sort(arr2))
print("\n")

#sorting a 2D array
arr3 = np.array([[3,2,4],[5,0,1]])
print("sorting 2D array", np.sort(arr3))
print("\n")

sorting numbers [0 1 2 3 6 8]


sorting string alphabetically ['apple' 'banana' 'cherry' 'orange']


sorting 2D array [[2 3 4]
 [0 1 5]]




In [45]:
#Filtering Array
#In Numpy we filter amn array using a boolean index list
#if the value of boolean index is true then it will pick thst element

import numpy as np
arr = np.array([10,12,13,14])
filter_arr = [True, False,True, False]#manually set the boolen index
newarr = arr[filter_arr]
print(newarr)

#creating the Filter array
arr1 = np.array([41,42,43,44,45])
filter_arr1 = []#emplty list where the geenrated boolean will store
for x in arr1:
    if x >42:
        filter_arr1.append(True)
    else:
        filter_arr1.append(False)
newarr1 = arr1[filter_arr1]
print(filter_arr1)
print(newarr1)

#create a filter array that will return only even elements from original array

arr2 =np.array([1,2,3,4,5,6,7,8,9,10])
filter_arr2 =[]
for x in arr2:
    if x%2==0:
        filter_arr2.append(True)
    else:
        filter_arr2.append(False)
newarr2 = arr2[filter_arr2]
print(filter_arr2)
print(newarr2)

[10 13]
[False, False, True, True, True]
[43 44 45]
[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]
